; PlatformIO Project Configuration File
;
; https://docs.platformio.org/page/projectconf.html

[env:Wemos_D1_Mini]
platform = espressif8266
board = d1_mini
framework = arduino
upload_protocol = esptool

[env:M5_ESP32]
platform = espressif32
board = m5stack-core-esp32
framework = arduino
upload_protocol = esptool

[env:Arduino_Nano]
platform = atmelavr
board = nanoatmega328
framework = arduino
upload_protocol = arduino

; -------------------------------------------------------
; Native test environments using EpoxyDuino (no hardware)
; -------------------------------------------------------

[env:epoxy-esp8266]
platform = native
lib_deps =
    https://github.com/bxparks/EpoxyDuino.git#v1.6.0
    bxparks/AUnit@^1.7.1
    https://github.com/LennartHennigs/Button2.git
lib_ldf_mode = deep+
lib_compat_mode = off
build_flags =
    -std=c++11
    -Wall
    -Wno-deprecated-declarations
    -DEPOXY_DUINO
    -DARDUINO_ESP8266
    -DESP8266
build_src_filter = +<*> -<examples/>
test_build_src = true

[env:epoxy-esp32]
platform = native
lib_deps =
    https://github.com/bxparks/EpoxyDuino.git#v1.6.0
    bxparks/AUnit@^1.7.1
    https://github.com/LennartHennigs/Button2.git
lib_ldf_mode = deep+
lib_compat_mode = off
build_flags =
    -std=c++11
    -Wall
    -Wno-deprecated-declarations
    -DEPOXY_DUINO
    -DARDUINO_ESP32
    -DESP32
    -DARDUINO_ARCH_ESP32
build_src_filter = +<*> -<examples/>
test_build_src = true

; -------------------------------------------------------
; Individual test suite environments
; -------------------------------------------------------

[env:test_basics]
platform = native
lib_deps =
    https://github.com/bxparks/EpoxyDuino.git#v1.6.0
    bxparks/AUnit@^1.7.1
    https://github.com/LennartHennigs/Button2.git
lib_ldf_mode = deep+
lib_compat_mode = off
lib_ignore = Unity
build_flags =
    -std=c++11
    -Wall
    -Wno-deprecated-declarations
    -DEPOXY_DUINO
    -DARDUINO_ESP8266
    -DESP8266
build_src_filter = +<*> -<examples/>
test_build_src = true
test_filter = test_basics

[env:test_matching]
platform = native
lib_deps =
    https://github.com/bxparks/EpoxyDuino.git#v1.6.0
    bxparks/AUnit@^1.7.1
    https://github.com/LennartHennigs/Button2.git
lib_ldf_mode = deep+
lib_compat_mode = off
lib_ignore = Unity
build_flags =
    -std=c++11
    -Wall
    -Wno-deprecated-declarations
    -DEPOXY_DUINO
    -DARDUINO_ESP8266
    -DESP8266
build_src_filter = +<*> -<examples/>
test_build_src = true
test_filter = test_matching

[env:test_callbacks]
platform = native
lib_deps =
    https://github.com/bxparks/EpoxyDuino.git#v1.6.0
    bxparks/AUnit@^1.7.1
    https://github.com/LennartHennigs/Button2.git
lib_ldf_mode = deep+
lib_compat_mode = off
lib_ignore = Unity
build_flags =
    -std=c++11
    -Wall
    -Wno-deprecated-declarations
    -DEPOXY_DUINO
    -DARDUINO_ESP8266
    -DESP8266
build_src_filter = +<*> -<examples/>
test_build_src = true
test_filter = test_callbacks
